export interface Tour {
  id: string
  slug: string
  title: string
  subtitle: string
  location: string
  country: string
  category: string
  categoryLabel: string
  dateStart: string
  dateEnd: string
  duration: string
  image: string
  description: string
  highlights: string[]
  includes: string[]
  excludes: string[]
  maxParticipants: number
  difficulty: 'Facile' | 'Moderato' | 'Avanzato'
  badge?: string
}

export const tours: Tour[] = [
  {
    id: '1',
    slug: 'grande-festa-del-calcio-roma',
    title: 'Grande Festa del Calcio',
    subtitle: 'Weekend calcistico nella Capitale',
    location: 'Roma, Italia',
    country: 'Italia',
    category: 'calcio',
    categoryLabel: 'Calcio',
    dateStart: '2026-05-15',
    dateEnd: '2026-05-17',
    duration: '3 giorni',
    image: '/images/tour-calcio-roma.jpg',
    description:
      "Immergiti nell'atmosfera elettrizzante del calcio italiano a Roma. Questo tour esclusivo ti porta a vivere una delle partite più attese della stagione nella città eterna, con trasferimenti premium, sistemazione in hotel 4 stelle nel cuore della capitale e una guida esperta dedicata al tuo gruppo. Prima della partita, scopri i luoghi iconici della storia sportiva romana con un tour guidato nei quartieri più autentici.",
    highlights: [
      'Biglietti premium con visuale ottimale',
      'Hotel 4 stelle in posizione centrale',
      'Tour pre-partita nei quartieri storici',
      'Trasferimenti privati inclusi',
      'Welcome dinner con specialità romane',
    ],
    includes: ['2 notti hotel 4*', 'Biglietti evento', 'Colazione inclusa', 'Trasferimenti aeroporto', 'Guida esperta'],
    excludes: ['Volo aereo', 'Pranzi e cene (escluso welcome dinner)', 'Spese personali'],
    maxParticipants: 20,
    difficulty: 'Facile',
    badge: 'Popolare',
  },
  {
    id: '2',
    slug: 'torneo-tennis-parigi',
    title: 'Torneo Tennis Parigi',
    subtitle: 'La terra rossa di Parigi in tutta la sua gloria',
    location: 'Parigi, Francia',
    country: 'Francia',
    category: 'tennis',
    categoryLabel: 'Tennis',
    dateStart: '2026-06-01',
    dateEnd: '2026-06-05',
    duration: '5 giorni',
    image: '/images/tour-tennis-parigi.jpg',
    description:
      "Vivi la magia del più grande torneo di tennis su terra battuta al mondo, nel cuore pulsante di Parigi. Cinque giorni immersi nell'eleganza parigina e nell'emozione di assistere ai migliori tennisti del pianeta. Il pacchetto include accesso ai campi principali e secondari, permettendoti di scoprire futuri campioni nei match preliminari. Serate libere per esplorare il fascino di Parigi, con consigli personalizzati della nostra guida locale.",
    highlights: [
      'Accesso multi-sessione ai campi principali',
      'Hotel boutique a 10 minuti dal complesso',
      'Visita guidata a Parigi con esperto di storia dello sport',
      'Degustazione di vini francesi',
      'Meet & greet con ex-professionisti',
    ],
    includes: ['4 notti hotel boutique 4*', 'Biglietti tornei (2 giornate)', 'Colazione inclusa', 'Trasferimenti interni', 'Guida bilingue'],
    excludes: ['Volo aereo', 'Visto (se richiesto)', 'Pranzi e cene', 'Spese personali'],
    maxParticipants: 15,
    difficulty: 'Facile',
    badge: 'Nuovo',
  },
  {
    id: '3',
    slug: 'gran-premio-monza',
    title: 'Gran Premio di Monza',
    subtitle: 'Il Tempio della Velocità ti aspetta',
    location: 'Monza, Italia',
    country: 'Italia',
    category: 'motorsport',
    categoryLabel: 'Motorsport',
    dateStart: '2026-09-04',
    dateEnd: '2026-09-07',
    duration: '4 giorni',
    image: '/images/tour-formula-monza.jpg',
    description:
      "Monza è il circuito più veloce del calendario di Formula 1 e il Gran Premio d'Italia è uno degli eventi più iconici dello sport motoristico mondiale. Questo tour ti porta all'interno di questa leggenda: tre giorni di gara (prove libere, qualifiche e gara), sistemazione a Monza e un'esperienza dietro le quinte con accesso alle zone hospitality. Senti il rombo dei motori, respira l'aria di benzina e carbone e unisciti ai tifosi più appassionati del mondo.",
    highlights: [
      'Biglietti 3 giorni (venerdì–domenica)',
      'Accesso alla zona paddock club',
      'Hotel 4* a Monza',
      'Trasferimento privato al circuito ogni giorno',
      'Cena esclusiva con ex-piloti',
    ],
    includes: ['3 notti hotel 4*', 'Biglietti 3 giorni gran premio', 'Paddock club', 'Trasferimenti giornalieri', 'Cena esclusiva'],
    excludes: ['Volo aereo', 'Pranzi', 'Merchandise', 'Spese personali'],
    maxParticipants: 12,
    difficulty: 'Facile',
    badge: 'VIP',
  },
  {
    id: '4',
    slug: 'tour-ciclismo-alpi',
    title: 'Tour Ciclismo sulle Alpi',
    subtitle: 'Le leggendarie salite alpine in diretta',
    location: 'Alpi Italiane e Francesi',
    country: 'Multi-paese',
    category: 'ciclismo',
    categoryLabel: 'Ciclismo',
    dateStart: '2026-07-14',
    dateEnd: '2026-07-19',
    duration: '6 giorni',
    image: '/images/tour-ciclismo-alpi.jpg',
    description:
      "Segui i più grandi campioni del ciclismo mentre scalano le vette più leggendarie delle Alpi. Questo tour di sei giorni ti porta al cuore delle tappe più attese della stagione ciclistica, con sistemazione in rifugi e hotel di charme lungo il percorso. Ogni giorno ci spostiamo strategicamente per assistere ai momenti clou: gli scatti sulle salite, gli sprint nei villaggi e l'arrivo in quota. Un'esperienza per veri appassionati di ciclismo che vogliono vivere la magia delle grandi salite dall'interno.",
    highlights: [
      'Posizioni privilegiate sulle salite più iconiche',
      'Minibus privato per spostarsi lungo il percorso',
      'Hotel di charme nelle Alpi',
      'Cena con ciclisti amatoriali locali',
      'Kit da ciclista in omaggio',
    ],
    includes: ['5 notti hotel/rifugi charme', 'Minibus privato 6 giorni', 'Tutti i pasti inclusi', 'Guide alpine', 'Kit esclusivo'],
    excludes: ['Volo aereo', 'Bevande alcoliche', 'Spese personali', 'Assicurazione'],
    maxParticipants: 10,
    difficulty: 'Moderato',
    badge: 'Avventura',
  },
  {
    id: '5',
    slug: 'basketball-madrid',
    title: 'Basketball Night Madrid',
    subtitle: 'La pallacanestro europea nella sua veste migliore',
    location: 'Madrid, Spagna',
    country: 'Spagna',
    category: 'basket',
    categoryLabel: 'Basket',
    dateStart: '2026-04-24',
    dateEnd: '2026-04-27',
    duration: '4 giorni',
    image: '/images/tour-basket-madrid.jpg',
    description:
      "La pallacanestro europea raggiunge il suo apice nei playoff e Madrid è una delle capitali indiscusse del basket continentale. Questo weekend speciale ti porta nella città più vivace della Spagna per assistere a una delle partite più attese della stagione. Tra un quarto e l'altro, esplora la movida madrilena, assaggia le tapas nel mercato centrale e lasciati trascinare dall'energia di una città che non dorme mai. Il trasporto da Madrid centro all'arena è incluso ogni sera.",
    highlights: [
      'Biglietti premium per 2 partite playoff',
      'Hotel 4* nel centro di Madrid',
      'Tour gastronomico incluso',
      'Trasferimenti serali all\'arena',
      'Guida locale esperta di basket',
    ],
    includes: ['3 notti hotel 4*', 'Biglietti 2 partite', 'Colazione inclusa', 'Tour gastronomico', 'Trasferimenti arena'],
    excludes: ['Volo aereo', 'Pranzi e cene', 'Bevande evento', 'Spese personali'],
    maxParticipants: 18,
    difficulty: 'Facile',
  },
  {
    id: '7',
    slug: 'rugby-londra',
    title: 'Rugby nel Cuore di Londra',
    subtitle: 'L\'emozione brutale del rugby internazionale',
    location: 'Londra, Regno Unito',
    country: 'Regno Unito',
    category: 'rugby',
    categoryLabel: 'Rugby',
    dateStart: '2026-11-07',
    dateEnd: '2026-11-10',
    duration: '4 giorni',
    image: '/images/tour-rugby-londra.jpg',
    description:
      "Londra ospita alcune delle partite di rugby più intense del calendario internazionale autunnale. Questo tour ti immerge nel mondo del rugby anglosassone: assisti a una delle sfide più attese tra le migliori nazionali d'Europa in uno degli stadi più maestosi della capitale britannica. Prima del calcio d'inizio, scopri i pub storici del centro con la nostra guida locale, dove la tradizione del rugby si respira ad ogni sorso di birra artigianale. Un'esperienza che unisce sport, cultura e il fascino inconfondibile di Londra.",
    highlights: [
      'Biglietti tribuna centrale con visuale perfetta',
      'Hotel 4* nel centro di Londra',
      'Pub tour pre-partita con guida locale',
      'Colazione inglese tradizionale ogni mattina',
      'Trasferimenti dallo stadio inclusi',
    ],
    includes: ['3 notti hotel 4*', 'Biglietti partita internazionale', 'Colazione inclusa', 'Pub tour', 'Trasferimenti stadio'],
    excludes: ['Volo aereo', 'Pranzi e cene', 'Spese personali', 'Visto (se richiesto)'],
    maxParticipants: 18,
    difficulty: 'Facile',
    badge: 'Autunno',
  },
  {
    id: '8',
    slug: 'sci-alpino-cortina',
    title: 'Coppa del Mondo di Sci a Cortina',
    subtitle: 'Adrenalina pura tra le Dolomiti innevate',
    location: 'Cortina d\'Ampezzo, Italia',
    country: 'Italia',
    category: 'sci',
    categoryLabel: 'Sci',
    dateStart: '2027-01-22',
    dateEnd: '2027-01-26',
    duration: '5 giorni',
    image: '/images/tour-sci-cortina.jpg',
    description:
      "Cortina d'Ampezzo è la regina delle Dolomiti e uno dei palcoscenici più scenografici dell'intero circuito di Coppa del Mondo. La mitica pista ospita le gare di discesa libera e super-G tra i campioni più veloci del pianeta, con le pareti verticali delle Dolomiti a fare da sfondo mozzafiato. Il pacchetto include sistemazione in uno chalet di lusso nel centro di Cortina, skipass per le giornate libere, e i migliori posti in tribuna per le gare. La sera, aperitivo in quota e cena con polenta e cervo nella migliore tradizione alpina.",
    highlights: [
      'Biglietti tribuna coperta per 2 gare',
      'Chalet 4* in centro a Cortina',
      'Skipass 3 giorni incluso',
      'Cena tipica alpina con prodotti locali',
      'Guida sci certificata per escursioni',
    ],
    includes: ['4 notti chalet 4*', 'Biglietti 2 gare Coppa del Mondo', 'Skipass 3 giorni', 'Mezza pensione', 'Guida sci'],
    excludes: ['Volo aereo', 'Noleggio sci/snowboard', 'Spese personali', 'Assicurazione sci'],
    maxParticipants: 12,
    difficulty: 'Moderato',
    badge: 'Inverno',
  },
  {
    id: '9',
    slug: 'nuoto-budapest',
    title: 'Campionati di Nuoto a Budapest',
    subtitle: 'Velocità e tecnica nella perla del Danubio',
    location: 'Budapest, Ungheria',
    country: 'Ungheria',
    category: 'nuoto',
    categoryLabel: 'Nuoto',
    dateStart: '2026-06-20',
    dateEnd: '2026-06-24',
    duration: '5 giorni',
    image: '/images/tour-nuoto-budapest.jpg',
    description:
      "Budapest è una delle capitali del nuoto europeo e la sua struttura olimpica è considerata tra le più belle e funzionali del mondo. Questo tour di cinque giorni ti porta al cuore dei campionati continentali, con accesso alle sessioni mattutine eliminatorie e alle finali serali, le più emozionanti. Budapest è anche una città straordinaria: terme storiche, architettura imperiale e una gastronomia ricca e sorprendente. Le nostre serate libere sono pensate per esplorare i rioni più autentici lungo il Danubio.",
    highlights: [
      'Biglietti per sessioni mattutine e finali serali',
      'Hotel 4* a Budapest con spa',
      'Giro in battello sul Danubio',
      'Visita alle terme Széchenyi',
      'Cena panoramica sul fiume',
    ],
    includes: ['4 notti hotel 4* con spa', 'Biglietti 4 sessioni', 'Colazione inclusa', 'Battello Danubio', 'Ingresso terme'],
    excludes: ['Volo aereo', 'Pranzi e cene (escluso cena panoramica)', 'Spese personali'],
    maxParticipants: 20,
    difficulty: 'Facile',
    badge: 'Cultura & Sport',
  },
  {
    id: '10',
    slug: 'vela-napoli',
    title: 'Regata Internazionale nel Golfo di Napoli',
    subtitle: 'Sport e mare, con il Vesuvio a fare da cornice',
    location: 'Napoli, Italia',
    country: 'Italia',
    category: 'vela',
    categoryLabel: 'Vela',
    dateStart: '2026-09-18',
    dateEnd: '2026-09-22',
    duration: '5 giorni',
    image: '/images/tour-vela-napoli.jpg',
    description:
      "Il Golfo di Napoli è uno dei teatri più suggestivi della vela internazionale: il Vesuvio sullo sfondo, le acque blu cobalto del Mediterraneo e le barche che volano sull'acqua spinte dal vento. Questa regata internazionale richiama i migliori equipaggi del mondo e il nostro tour ti permette di seguirla dall'acqua, a bordo di uno yatch privato che segue le regate lungo il percorso. Il tutto abbinato alla gastronomia napoletana più autentica: pizza, frittura di paranza e limoncello sotto le stelle.",
    highlights: [
      'Yacht privato per seguire le regate',
      'Hotel 4* sul lungomare di Napoli',
      'Cena di pizza con vista sul porto',
      'Gita a Capri inclusa',
      'Welcome cocktail a bordo al tramonto',
    ],
    includes: ['4 notti hotel 4* sul mare', 'Yacht privato 2 giorni', 'Gita Capri', 'Welcome cocktail', 'Guida nautica'],
    excludes: ['Volo aereo', 'Pranzi e cene (esclusa pizza)', 'Spese personali', 'Assicurazione'],
    maxParticipants: 10,
    difficulty: 'Facile',
    badge: 'Esclusivo',
  },
  {
    id: '11',
    slug: 'boxe-amsterdam',
    title: 'Notte di Boxe ad Amsterdam',
    subtitle: 'Pugni, passione e la capitale europea per eccellenza',
    location: 'Amsterdam, Paesi Bassi',
    country: 'Paesi Bassi',
    category: 'boxe',
    categoryLabel: 'Boxe',
    dateStart: '2026-10-17',
    dateEnd: '2026-10-20',
    duration: '4 giorni',
    image: '/images/tour-boxe-amsterdam.jpg',
    description:
      "Amsterdam ospita una serata di boxe professionistica che concentra i migliori pugili europei in un unico evento spettacolare. Il programma della serata include diversi incontri preliminari e il match principale per il titolo europeo, in un'arena che crea un'atmosfera unica tra luci, musica e l'urlo del pubblico. Il tour è pensato per chi vuole combinare lo spettacolo della boxe con la scoperta di una delle città più affascinanti d'Europa: canali, musei di livello mondiale e una scena gastronomica sorprendente.",
    highlights: [
      'Biglietti ringside per l\'evento principale',
      'Hotel design 4* nel cuore di Amsterdam',
      'Cena olandese tipica nel Jordaan',
      'Tour in bicicletta tra i canali',
      'Meet & greet con atleti pre-evento',
    ],
    includes: ['3 notti hotel design 4*', 'Biglietti evento boxe (ringside)', 'Colazione inclusa', 'Tour in bici', 'Meet & greet'],
    excludes: ['Volo aereo', 'Pranzi e cene (esclusa cena tipica)', 'Spese personali'],
    maxParticipants: 14,
    difficulty: 'Facile',
    badge: 'Notte Speciale',
  },
  {
    id: '6',
    slug: 'atletica-berlino',
    title: 'Campionati Europei di Atletica',
    subtitle: 'La velocità e la potenza dell\'atletica leggera',
    location: 'Berlino, Germania',
    country: 'Germania',
    category: 'atletica',
    categoryLabel: 'Atletica',
    dateStart: '2026-08-10',
    dateEnd: '2026-08-14',
    duration: '5 giorni',
    image: '/images/tour-atletica-berlino.jpg',
    description:
      "Berlino ospita i Campionati Europei di Atletica Leggera in uno degli stadi più iconici del continente. Cinque giorni di pura adrenalina: sprint dei 100 metri, salti in alto, lanci e maratona finale nelle strade della capitale tedesca. Il pacchetto include accesso alle sessioni serali, le più spettacolari con le finali delle gare principali, e alle sessioni diurne per seguire le eliminatorie. Berlino è anche una città straordinaria da esplorare: arte, storia e cultura ad ogni angolo.",
    highlights: [
      'Accesso a 4 sessioni del campionato',
      'Hotel 4* a 5 minuti dallo stadio',
      'Tour storico di Berlino incluso',
      'Cena panoramica con vista sulla città',
      'Guida italiana dedicata',
    ],
    includes: ['4 notti hotel 4*', 'Biglietti 4 sessioni', 'Colazione inclusa', 'Tour Berlino', 'Cena panoramica', 'Guida italiana'],
    excludes: ['Volo aereo', 'Pranzi e cene (escluso cena panoramica)', 'Spese personali'],
    maxParticipants: 16,
    difficulty: 'Facile',
    badge: 'Best Value',
  },
]

export const categories = [
  { value: 'tutti', label: 'Tutti i Tour' },
  { value: 'calcio', label: 'Calcio' },
  { value: 'tennis', label: 'Tennis' },
  { value: 'motorsport', label: 'Motorsport' },
  { value: 'ciclismo', label: 'Ciclismo' },
  { value: 'basket', label: 'Basket' },
  { value: 'atletica', label: 'Atletica' },
  { value: 'rugby', label: 'Rugby' },
  { value: 'sci', label: 'Sci' },
  { value: 'nuoto', label: 'Nuoto' },
  { value: 'vela', label: 'Vela' },
  { value: 'boxe', label: 'Boxe' },
]

export const countries = [
  { value: 'tutti', label: 'Tutti i Paesi' },
  { value: 'Italia', label: 'Italia' },
  { value: 'Francia', label: 'Francia' },
  { value: 'Spagna', label: 'Spagna' },
  { value: 'Germania', label: 'Germania' },
  { value: 'Regno Unito', label: 'Regno Unito' },
  { value: 'Ungheria', label: 'Ungheria' },
  { value: 'Paesi Bassi', label: 'Paesi Bassi' },
  { value: 'Multi-paese', label: 'Multi-paese' },
]
