export interface Tour {
  id: string
  slug: string
  title: string
  subtitle: string
  location: string
  country: string
  category: string
  categoryLabel: string
  dateStart: string
  dateEnd: string
  duration: string
  image: string
  description: string
  highlights: string[]
  includes: string[]
  excludes: string[]
  maxParticipants: number
  difficulty: 'Facile' | 'Moderato' | 'Avanzato'
  badge?: string
}

export const tours: Tour[] = [
  {
    id: '1',
    slug: 'velo-toscana',
    title: 'Pedalando tra i Vigneti della Toscana',
    subtitle: 'Cicloturismo d\'autore tra colline, borghi e sapori',
    location: 'Siena – Montalcino – Val d\'Orcia, Italia',
    country: 'Italia',
    category: 'ciclismo',
    categoryLabel: 'Ciclismo',
    dateStart: '2026-05-09',
    dateEnd: '2026-05-14',
    duration: '6 giorni',
    image: '/images/tour-velo-toscana.jpg',
    description:
      'Un viaggio lento e autentico attraverso uno dei paesaggi più belli d\'Italia. Ogni mattina si parte da un agriturismo diverso lungo strade bianche che attraversano vigneti, oliveti e borghi medievali. Le tappe giornaliere sono di 50–70 km su percorsi misti asfalto e sterrato, adatte a ciclisti con buona preparazione di base. Le salite verso Montalcino e Pienza regalano panorami che valgono ogni goccia di sudore. La sera si cena con prodotti del territorio: pecorino, cinghiale in umido, Brunello. Le bici da gravel sono incluse nel pacchetto o puoi portare la tua.',
    highlights: [
      'Percorsi esclusivi su strade bianche e asfalto',
      'Pernottamenti in agriturismi con piscina',
      'Cene con prodotti del territorio incluse',
      'Bici da gravel di alto livello disponibili',
      'Guida cicloturistica certificata',
    ],
    includes: ['5 notti in agriturismo 4*', 'Bici da gravel (opzionale)', 'Mezza pensione', 'Guida esperta', 'Supporto meccanico'],
    excludes: ['Trasporto verso Siena', 'Bevande ai pasti', 'Mance', 'Assicurazione personale'],
    maxParticipants: 10,
    difficulty: 'Moderato',
    badge: 'Popolare',
  },
  {
    id: '2',
    slug: 'moto-dolomiti',
    title: 'Moto Tour tra le Dolomiti',
    subtitle: 'I passi più leggendari delle Alpi in sella alla tua moto',
    location: 'Bolzano – Cortina – Trento, Italia',
    country: 'Italia',
    category: 'moto',
    categoryLabel: 'Moto Tour',
    dateStart: '2026-06-13',
    dateEnd: '2026-06-18',
    duration: '6 giorni',
    image: '/images/tour-moto-dolomiti.jpg',
    description:
      'Sei passi alpini, tre valli e oltre 800 km di asfalto perfetto tra le vette più spettacolari d\'Europa. Il tour tocca alcuni dei tornanti più famosi delle Alpi orientali, alternando tratti veloci di fondovalle a salite mozzafiato su asfalto curato e privo di traffico. Ogni tappa si conclude in un hotel di montagna con sauna e cucina altoatesina. Il tour è adatto a motociclisti con esperienza su strade di montagna. Ogni partecipante viaggia con la propria moto: nessun noleggio imposto, nessun gruppo guidato rigido.',
    highlights: [
      'Itinerario su 6 passi alpini iconici',
      'Hotel 4* di montagna con sauna ogni sera',
      'Briefing mattutino e roadbook dettagliato',
      'Meccanico di supporto incluso',
      'Cena a base di specialità altoatesine',
    ],
    includes: ['5 notti hotel 4* di montagna', 'Mezza pensione', 'Roadbook e briefing giornaliero', 'Supporto tecnico', 'Assistenza stradale'],
    excludes: ['Moto propria necessaria', 'Carburante', 'Pedaggi autostradali', 'Assicurazione moto'],
    maxParticipants: 12,
    difficulty: 'Moderato',
    badge: 'Avventura',
  },
  {
    id: '3',
    slug: 'cammini-roma',
    title: 'Roma a Passo Lento — Cammini d’Autore',
    subtitle: 'Via Appia, parchi e panorami: la città eterna fuori rotta',
    location: 'Roma, Italia',
    country: 'Italia',
    category: 'trekking',
    categoryLabel: 'Trekking',
    dateStart: '2026-04-19',
    dateEnd: '2026-04-22',
    duration: '4 giorni',
    image: '/images/tour-maratona-roma.jpg',
    description:
      'Un weekend lungo per scoprire Roma con un ritmo diverso: cammini urbani e tratti verdi lungo la Via Appia Antica, parchi storici e belvedere al tramonto. Ogni giornata alterna 10–16 km di passeggiate guidate e soste nei quartieri più autentici, con tempo libero per musei, mercati e trattorie. Il programma è pensato per chi ama esplorare a piedi senza fretta, con tappe ben bilanciate e logistica semplice.',
    highlights: [
      'Cammini guidati tra Via Appia e parchi di Roma',
      'Itinerari “fuori rotta” e punti panoramici al tramonto',
      'Hotel 4* comodo per muoversi a piedi e in metro',
      'Consigli gastronomici e soste selezionate',
      'Gruppo piccolo e ritmo rilassato',
    ],
    includes: ['3 notti hotel 4* centrale', 'Passeggiate guidate', 'Mappe e tracce del percorso', 'Assistenza organizzativa'],
    excludes: ['Volo aereo', 'Pranzi', 'Trasporto dalla stazione', 'Spese personali'],
    maxParticipants: 20,
    difficulty: 'Facile',
    badge: 'Nuovo',
  },
  {
    id: '4',
    slug: 'trekking-alpi',
    title: 'Alta Via delle Alpi — Trekking d\'Autore',
    subtitle: '5 giorni tra ghiacciai, rifugi e silenzi alpini',
    location: 'Valle d\'Aosta – Alto Adige, Italia',
    country: 'Italia',
    category: 'trekking',
    categoryLabel: 'Trekking',
    dateStart: '2026-07-26',
    dateEnd: '2026-07-31',
    duration: '6 giorni',
    image: '/images/tour-trekking-alpi.jpg',
    description:
      'Un trekking impegnativo e magnifico sulle alte quote delle Alpi italiane, in piccoli gruppi di massimo 8 persone. Il percorso si svolge su sentieri segnalati e non, con dislivelli giornalieri tra 600 e 1000 metri. Si dorme nei rifugi alpini più caratteristici, cenando con zuppa d\'orzo e canederli a lume di candela. Le giornate iniziano all\'alba per godere dei panorami sui ghiacciai prima che le nuvole li nascondano. La guida alpina certificata conosce ogni sentiero, ogni marmotta e ogni storia di queste montagne.',
    highlights: [
      'Percorso su alta via con guida alpina certificata',
      'Pernottamenti in rifugi alpini storici',
      'Vitto completo in rifugio incluso',
      'Attrezzatura tecnica verificata alla partenza',
      'Gruppo massimo 8 persone per un\'esperienza autentica',
    ],
    includes: ['5 notti in rifugio alpino', 'Pensione completa in rifugio', 'Guida alpina certificata', 'Kit primo soccorso', 'Mappa e GPS'],
    excludes: ['Trasporto al punto di partenza', 'Attrezzatura personale', 'Assicurazione alpinistica', 'Bevande alcoliche'],
    maxParticipants: 8,
    difficulty: 'Avanzato',
    badge: 'Esclusivo',
  },
  {
    id: '5',
    slug: 'kayak-sicilia',
    title: 'Kayak d\'Altura lungo la Costa Siciliana',
    subtitle: 'Grotte, calette e tramonti sul Mediterraneo a colpi di pagaia',
    location: 'Palermo – Castellammare – Trapani, Italia',
    country: 'Italia',
    category: 'kayak',
    categoryLabel: 'Kayak',
    dateStart: '2026-06-27',
    dateEnd: '2026-07-02',
    duration: '6 giorni',
    image: '/images/tour-kayak-sicilia.jpg',
    description:
      'La costa nord-occidentale della Sicilia è tra le più selvagge e spettacolari del Mediterraneo: grotte marine, faraglioni di tufo giallo, acque trasparenti e calette raggiungibili solo dal mare. Questo tour in kayak da mare accompagna gruppi di massimo 10 persone lungo oltre 120 km di costa, con sbarchi sulle spiagge più inaccessibili. Si dorme in agriturismi fronte mare e si cena con il pesce pescato localmente. Non è richiesta esperienza di kayak: la formazione tecnica è inclusa nel primo giorno.',
    highlights: [
      'Oltre 120 km di costa siciliana inaccessibile via terra',
      'Grotte marine e calette esclusive',
      'Kayak da mare inclusi e certificati',
      'Corso base di kayak il primo giorno',
      'Cene con pesce fresco locale ogni sera',
    ],
    includes: ['5 notti in agriturismo fronte mare', 'Kayak e attrezzatura completa', 'Istruttore federale', 'Pensione completa', 'Supporto barca'],
    excludes: ['Trasporto verso Palermo', 'Mance', 'Bevande alcoliche', 'Assicurazione personale'],
    maxParticipants: 10,
    difficulty: 'Moderato',
    badge: 'Estate',
  },
  {
    id: '6',
    slug: 'sci-fondo-abruzzo',
    title: 'Sci di Fondo nei Boschi d\'Abruzzo',
    subtitle: 'Silenzio, neve e natura nel cuore degli Appennini',
    location: 'Parco Nazionale d\'Abruzzo, Italia',
    country: 'Italia',
    category: 'sci',
    categoryLabel: 'Sci di Fondo',
    dateStart: '2027-01-10',
    dateEnd: '2027-01-15',
    duration: '6 giorni',
    image: '/images/tour-sci-fondo-abruzzo.jpg',
    description:
      'Il Parco Nazionale d\'Abruzzo è uno degli ultimi angoli di natura incontaminata d\'Italia: cervi, camosci e lupi condividono i boschi con chi sa muoversi in silenzio. Lo sci di fondo è il modo perfetto per esplorare questi paesaggi invernali. Il tour prevede uscite giornaliere di 15–25 km su piste battute e percorsi fuori traccia, accompagnati da una guida esperta di fauna locale. La sera, massaggio incluso e cena con tartufo nero di Norcia e formaggi pecorino d\'Appennino.',
    highlights: [
      'Percorsi esclusivi nel Parco Nazionale',
      'Avvistamento di fauna alpina guidato',
      'Sci di fondo e sci escursionismo disponibili',
      'Massaggio rilassante serale incluso',
      'Cena con specialità abruzzesi inclusa',
    ],
    includes: ['5 notti chalet 4*', 'Sci da fondo o escursionismo', 'Guida naturalistica', 'Mezza pensione', 'Massaggio giornaliero'],
    excludes: ['Trasporto verso il parco', 'Noleggio abbigliamento tecnico', 'Bevande alcoliche', 'Assicurazione'],
    maxParticipants: 10,
    difficulty: 'Moderato',
    badge: 'Inverno',
  },
  {
    id: '7',
    slug: 'trail-pirenei',
    title: 'Trekking tra i Pirenei',
    subtitle: 'Creste, valichi e panorami infiniti tra Spagna e Francia',
    location: 'Pirenei Aragonesi, Spagna',
    country: 'Spagna',
    category: 'trekking',
    categoryLabel: 'Trekking',
    dateStart: '2026-09-05',
    dateEnd: '2026-09-10',
    duration: '6 giorni',
    image: '/images/tour-trail-pirenei.jpg',
    description:
      'I Pirenei aragonesi offrono alcuni dei sentieri di alta montagna più emozionanti d\'Europa: creste ventose, laghi glaciali, boschi di pini silvestri e valichi a oltre 2500 metri. Questo trekking è pensato per camminatori abituati alla montagna, con uscite giornaliere di 12–18 km e dislivelli importanti. Si parte ogni mattina dall\'hotel boutique nel villaggio di Hecho per esplorare un settore diverso del massiccio. La sera si recupera con bagno nel rio glaciale e cena aragonese.',
    highlights: [
      'Sentieri di alta montagna tra creste e laghi glaciali',
      'Piccolo gruppo (max 8 persone)',
      'Guida esperta di montagna',
      'Hotel boutique nel villaggio storico di Hecho',
      'Itinerario adattabile al meteo',
    ],
    includes: ['5 notti hotel boutique', 'Guida esperta', 'Mappa GPS e roadbook', 'Mezza pensione', 'Assistenza organizzativa'],
    excludes: ['Volo verso Saragozza', 'Attrezzatura personale', 'Assicurazione personale', 'Spese personali'],
    maxParticipants: 8,
    difficulty: 'Avanzato',
    badge: 'Autunno',
  },
  {
    id: '8',
    slug: 'velo-costa-amalfi',
    title: 'Cicloturismo sulla Costiera Amalfitana',
    subtitle: 'Il mare più blu d\'Italia visto da una sella',
    location: 'Napoli – Positano – Ravello – Salerno, Italia',
    country: 'Italia',
    category: 'ciclismo',
    categoryLabel: 'Ciclismo',
    dateStart: '2026-10-03',
    dateEnd: '2026-10-07',
    duration: '5 giorni',
    image: '/images/tour-velo-costa-amalfi.jpg',
    description:
      'La strada statale della Costiera Amalfitana è famosa in tutto il mondo per i suoi tornanti a picco sul mare, i limoneti terrazzati e i borghi arrampicati sulle rocce. In autunno, con meno traffico e una luce dorata che trasforma ogni scorcio in un dipinto, è il momento perfetto per percorrerla in bici. Il tour si svolge su e-bike di alto livello con assistenza regolabile, rendendolo accessibile anche a chi non si allena regolarmente. Ogni giornata si conclude con un aperitivo fronte mare.',
    highlights: [
      'Percorso completo Napoli–Salerno in e-bike',
      'E-bike di alto livello incluse',
      'Hotel boutique con vista mare ogni sera',
      'Aperitivo fronte mare ogni sera incluso',
      'Soste guidate nei borghi storici',
    ],
    includes: ['4 notti hotel boutique 4* fronte mare', 'E-bike premium', 'Guida cicloturistica', 'Colazione inclusa', 'Aperitivo serale'],
    excludes: ['Trasporto verso Napoli', 'Pranzi e cene', 'Mance', 'Assicurazione'],
    maxParticipants: 12,
    difficulty: 'Facile',
    badge: 'Romantico',
  },
  {
    id: '9',
    slug: 'arrampicata-sardegna',
    title: 'Arrampicata sulle Falesie di Sardegna',
    subtitle: 'Calcare, mare e adrenalina nella roccia più bella d\'Italia',
    location: 'Cala Gonone – Baunei – Orosei, Italia',
    country: 'Italia',
    category: 'arrampicata',
    categoryLabel: 'Arrampicata',
    dateStart: '2026-05-23',
    dateEnd: '2026-05-28',
    duration: '6 giorni',
    image: '/images/tour-arrampicata-sardegna.jpg',
    description:
      'Le falesie calcaree del Golfo di Orosei sono tra le più belle d\'Europa: vie di tutti i livelli, dalla 4a alla 8b+, su roccia compatta che si affaccia direttamente sul mare cristallino. Il tour è guidato da istruttori federali con anni di esperienza in Sardegna e propone una selezione di vie adatte a ogni livello, dal principiante allo specialista. Le mattine si arrampica, i pomeriggi si nuota in calette raggiungibili solo a piedi o in gommone. La sera si dorme in un b&b con vista sul golfo.',
    highlights: [
      'Falesie marine con vie per tutti i livelli',
      'Istruttori federali di arrampicata',
      'Attrezzatura tecnica completa inclusa',
      'Gommone per raggiungere calette segrete',
      'B&B panoramico sul Golfo di Orosei',
    ],
    includes: ['5 notti b&b panoramico', 'Istruttori federali (2)', 'Attrezzatura completa', 'Gommone giornaliero', 'Colazione inclusa'],
    excludes: ['Volo verso Cagliari/Olbia', 'Pranzi e cene', 'Scarpe da arrampicata', 'Assicurazione'],
    maxParticipants: 8,
    difficulty: 'Moderato',
    badge: 'Adrenalina',
  },
  {
    id: '10',
    slug: 'moto-balcani',
    title: 'Moto Tour attraverso i Balcani',
    subtitle: 'Strade dimenticate, villaggi medievali e ospitalità autentica',
    location: 'Slovenia – Croazia – Bosnia, Multi-paese',
    country: 'Multi-paese',
    category: 'moto',
    categoryLabel: 'Moto Tour',
    dateStart: '2026-08-22',
    dateEnd: '2026-08-31',
    duration: '10 giorni',
    image: '/images/tour-moto-balcani.jpg',
    description:
      'I Balcani sono il segreto meglio custodito del mototurismo europeo: strade di montagna deserte, foreste primordiali, borghi di pietra incontaminati e una cucina sincera che racconta secoli di storia. Questo tour attraversa tre paesi in dieci giorni, percorrendo oltre 2000 km su asfalto e sterrato selezionato. Si dorme in piccole pensioni a conduzione familiare, si mangia nei ristoranti dove non si vede mai un menù in inglese. La guida parla italiano, conosce ogni km dell\'itinerario e ogni trattoria nascosta.',
    highlights: [
      'Oltre 2000 km su strade di alta montagna',
      'Tre paesi: Slovenia, Croazia, Bosnia',
      'Guide italofone con esperienza nei Balcani',
      'Pensioni a conduzione familiare selezionate',
      'Itinerario flessibile adattabile al meteo',
    ],
    includes: ['9 notti in pensioni selezionate', 'Mezza pensione', 'Guide bilingui', 'Supporto meccanico', 'Assistenza stradale 24h'],
    excludes: ['Moto propria necessaria', 'Carburante', 'Visto (se richiesto)', 'Assicurazione moto'],
    maxParticipants: 10,
    difficulty: 'Moderato',
    badge: 'Multi-Paese',
  },
  {
    id: '11',
    slug: 'velo-provenza',
    title: 'Velo Tour in Provenza tra Lavanda e Vento',
    subtitle: 'I campi viola, i mercati provenzali e il Mistral in faccia',
    location: 'Avignone – Luberon – Verdon, Francia',
    country: 'Francia',
    category: 'ciclismo',
    categoryLabel: 'Ciclismo',
    dateStart: '2026-07-04',
    dateEnd: '2026-07-09',
    duration: '6 giorni',
    image: '/images/tour-velo-provenza.jpg',
    description:
      'La Provenza in luglio è un\'esplosione di colori: i campi di lavanda in fiore trasformano il paesaggio in una tavolozza impressionista. In bici è il modo migliore per immergersi in questa bellezza lenta, fermandosi nei mercati dei villaggi, visitando frantoi e cantine artigianali. Le tappe giornaliere di 60–80 km attraversano il Luberon, le Gorge du Verdon e gli altopiani di Valensole. Si dorme in maisons de charme selezionate a mano e si cena con ratatouille, tapenade e rosé locale.',
    highlights: [
      'Percorsi esclusivi tra i campi di lavanda in fiore',
      'Maisons de charme selezionate ogni sera',
      'Degustazione vini e olio locale inclusa',
      'Bici da strada o e-bike a scelta',
      'Guida italiana con esperienza in Provenza',
    ],
    includes: ['5 notti maisons de charme 4*', 'Bici da strada o e-bike', 'Mezza pensione', 'Degustazioni', 'Guida esperta'],
    excludes: ['Volo verso Marsiglia/Avignone', 'Pranzi', 'Bevande alcoliche extra', 'Assicurazione'],
    maxParticipants: 10,
    difficulty: 'Moderato',
    badge: 'Estate',
  },
]

export const categories = [
  { value: 'tutti', label: 'Tutti i Tour' },
  { value: 'ciclismo', label: 'Ciclismo' },
  { value: 'moto', label: 'Moto Tour' },
  { value: 'trekking', label: 'Trekking' },
  { value: 'kayak', label: 'Kayak' },
  { value: 'sci', label: 'Sci di Fondo' },
  { value: 'arrampicata', label: 'Arrampicata' },
]

export const countries = [
  { value: 'tutti', label: 'Tutti i Paesi' },
  { value: 'Italia', label: 'Italia' },
  { value: 'Francia', label: 'Francia' },
  { value: 'Spagna', label: 'Spagna' },
  { value: 'Multi-paese', label: 'Multi-paese' },
]
